server:
  port: 8010

mybatis:
    mapper-locations: classpath:mapper/*/*.xml

spring:
  application:
    name: ServerPatrol
  profiles:
    active: dev
  #thymeleaf:
    #mode: LEGACYHTML5
    #cache: false
